version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      runas: ec2-user
